import type { BigVWorkbenchSnapshot } from "./types";

export const BIGV_WORKBENCH_SNAPSHOT: BigVWorkbenchSnapshot = {
  nav: [
    {
      key: "danmaku",
      label: "弹幕姬",
      to: "/danmaku",
      description: "实时互动流、投递状态与启停控制",
    },
    {
      key: "quota",
      label: "额度检查",
      to: "/quota",
      description: "查看请求消耗、token 走势与子系统拆分",
    },
    {
      key: "audience",
      label: "观众信息",
      to: "/audience",
      description: "观众人设、长期记忆和互动偏好",
    },
    {
      key: "review",
      label: "直播回顾",
      to: "/review",
      description: "主播画像、场次摘要、高光行为与建议",
    },
  ],
  danmaku: {
    liveStatus: {
      roomLabel: "本地单直播间 / 房间 1001",
      streamTitle: "晚间试玩 + 主播语音主链路验证",
      statusLabel: "模拟直播中",
      tone: "warn",
      viewerEstimate: 186,
      rhythmLabel: "平稳升温",
      nextActionHint: "当前允许轻量礼物和高频弹幕，暂不建议连续 SC。",
      updatedAt: "2 分钟前",
    },
    inputSources: [
      {
        key: "voice",
        label: "主播语音",
        statusLabel: "待输入",
        tone: "info",
        summary: "等待本地 ASR 或手动面板提交主播语音文本。",
      },
      {
        key: "echo-live",
        label: "Echo-Live",
        statusLabel: "预留接口",
        tone: "info",
        summary: "Echo-Live 输入适配器已预留，阶段 3 不接入真实事件。",
      },
      {
        key: "vision",
        label: "视觉上下文",
        statusLabel: "预留接口",
        tone: "info",
        summary: "视觉摘要输入接口已预留，阶段 3 不处理原始视频流。",
      },
    ],
    contextEvents: [],
    contextWindowSeconds: 300,
    toggles: [
      {
        key: "dispatch",
        label: "自动投递",
        description: "控制本地模拟事件是否进入互动渲染队列。",
        enabled: true,
      },
      {
        key: "gifts",
        label: "礼物通道",
        description: "允许生成 gift 与 membership 相关互动。",
        enabled: true,
      },
      {
        key: "super-chat",
        label: "SC 通道",
        description: "高价值互动默认谨慎开启，用于节奏验证。",
        enabled: false,
      },
      {
        key: "memory-write",
        label: "记忆写回预演",
        description: "仅展示前端状态，不会写入真实记忆库。",
        enabled: true,
      },
    ],
    queueStats: [
      { type: "danmaku", label: "弹幕", queued: 12, delivered: 148, throttled: 6 },
      { type: "gift", label: "礼物", queued: 2, delivered: 16, throttled: 1 },
      { type: "super_chat", label: "SC", queued: 0, delivered: 3, throttled: 2 },
      { type: "membership", label: "舰长", queued: 1, delivered: 4, throttled: 0 },
    ],
    recentEvents: [
      {
        id: "evt-1",
        type: "danmaku",
        audienceName: "阿黎",
        content: "这一段反应好快，像是真的在跟弹幕对线。",
        statusLabel: "已投递",
        tone: "ok",
        happenedAt: "20:41:13",
      },
      {
        id: "evt-2",
        type: "gift",
        audienceName: "北街舟",
        content: "送出荧光棒 x2，配合主播刚提到的新梗。",
        amountLabel: "¥20",
        statusLabel: "已投递",
        tone: "ok",
        happenedAt: "20:40:57",
      },
      {
        id: "evt-3",
        type: "super_chat",
        audienceName: "糖霜六号",
        content: "建议下一段切回剧情点评，不要一直卡在设置界面。",
        amountLabel: "¥30",
        statusLabel: "被节流",
        tone: "warn",
        happenedAt: "20:40:28",
      },
      {
        id: "evt-4",
        type: "membership",
        audienceName: "镜岛",
        content: "触发舰长入场欢迎，但尚未进入真实平台链路。",
        statusLabel: "排队中",
        tone: "info",
        happenedAt: "20:39:49",
      },
    ],
    mockSource: {
      state: "idle",
      scenarioLabel: "本地直播循环",
      tickCount: 0,
      intervalMs: 2500,
    },
    mockSourceRecords: [],
    notices: [
      {
        id: "notice-2",
        title: "SC 通道关闭",
        detail: "当前仅做前端模拟，不建议持续放开高价值互动。",
        tone: "info",
      },
      {
        id: "notice-3",
        title: "记忆写回未接通",
        detail: "页面仅演示写回条件与提示，不会污染真实长期记忆。",
        tone: "warn",
      },
    ],
  },
  quota: {
    defaultWindow: "24h",
    windows: [
      { key: "24h", label: "24 小时" },
      { key: "7d", label: "7 天" },
      { key: "30d", label: "30 天" },
    ],
    windowData: {
      "24h": {
        summary: {
          requestCount: 246,
          inputTokens: 318400,
          outputTokens: 92600,
          estimatedCost: 38.72,
          retryWasteTokens: 18240,
        },
        trend: [
          { label: "00", value: 2200 },
          { label: "04", value: 1800 },
          { label: "08", value: 4200 },
          { label: "12", value: 5600 },
          { label: "16", value: 6900 },
          { label: "20", value: 8400 },
        ],
        byModel: [
          { id: "gpt-4.1-mini", label: "gpt-4.1-mini", value: 214000, share: 52, tone: "ok" },
          { id: "gpt-4.1", label: "gpt-4.1", value: 121000, share: 29, tone: "warn" },
          { id: "embedding", label: "text-embedding-3-small", value: 76000, share: 19, tone: "info" },
        ],
        byCapability: [
          { id: "gen", label: "互动生成", value: 196000, share: 48, tone: "ok" },
          { id: "memory", label: "记忆检索", value: 94000, share: 23, tone: "info" },
          { id: "summary", label: "场次摘要", value: 62000, share: 15, tone: "warn" },
          { id: "retry", label: "失败重试", value: 58240, share: 14, tone: "error" },
        ],
        bySubsystem: [
          { id: "provider", label: "Provider 请求", value: 41, share: 41, tone: "ok", helperText: "峰值每小时 18 次" },
          { id: "planner", label: "观众编排", value: 24, share: 24, tone: "info", helperText: "含频率控制预演" },
          { id: "memory", label: "记忆层", value: 21, share: 21, tone: "warn", helperText: "写回仍为模拟" },
          { id: "emitter", label: "投递层", value: 14, share: 14, tone: "error", helperText: "节流主要发生在 SC 通道" },
        ],
      },
      "7d": {
        summary: {
          requestCount: 1286,
          inputTokens: 1723400,
          outputTokens: 498600,
          estimatedCost: 216.84,
          retryWasteTokens: 94520,
        },
        trend: [
          { label: "周一", value: 10200 },
          { label: "周二", value: 11800 },
          { label: "周三", value: 14600 },
          { label: "周四", value: 12800 },
          { label: "周五", value: 17400 },
          { label: "周六", value: 22000 },
          { label: "周日", value: 19600 },
        ],
        byModel: [
          { id: "gpt-4.1-mini", label: "gpt-4.1-mini", value: 1128000, share: 51, tone: "ok" },
          { id: "gpt-4.1", label: "gpt-4.1", value: 656000, share: 30, tone: "warn" },
          { id: "embedding", label: "text-embedding-3-small", value: 437000, share: 19, tone: "info" },
        ],
        byCapability: [
          { id: "gen", label: "互动生成", value: 936000, share: 42, tone: "ok" },
          { id: "memory", label: "记忆检索", value: 514000, share: 23, tone: "info" },
          { id: "summary", label: "场次摘要", value: 398000, share: 18, tone: "warn" },
          { id: "retry", label: "失败重试", value: 373000, share: 17, tone: "error" },
        ],
        bySubsystem: [
          { id: "provider", label: "Provider 请求", value: 39, share: 39, tone: "ok", helperText: "平均成功率 93%" },
          { id: "planner", label: "观众编排", value: 23, share: 23, tone: "info", helperText: "高峰时段策略更活跃" },
          { id: "memory", label: "记忆层", value: 22, share: 22, tone: "warn", helperText: "摘要轮次明显增加" },
          { id: "emitter", label: "投递层", value: 16, share: 16, tone: "error", helperText: "重试主要来自事件拥塞" },
        ],
      },
      "30d": {
        summary: {
          requestCount: 4820,
          inputTokens: 6482300,
          outputTokens: 1921400,
          estimatedCost: 804.16,
          retryWasteTokens: 322600,
        },
        trend: [
          { label: "第 1 周", value: 58200 },
          { label: "第 2 周", value: 68400 },
          { label: "第 3 周", value: 74200 },
          { label: "第 4 周", value: 81600 },
        ],
        byModel: [
          { id: "gpt-4.1-mini", label: "gpt-4.1-mini", value: 4140000, share: 49, tone: "ok" },
          { id: "gpt-4.1", label: "gpt-4.1", value: 2570000, share: 31, tone: "warn" },
          { id: "embedding", label: "text-embedding-3-small", value: 1691700, share: 20, tone: "info" },
        ],
        byCapability: [
          { id: "gen", label: "互动生成", value: 3460000, share: 41, tone: "ok" },
          { id: "memory", label: "记忆检索", value: 1890000, share: 22, tone: "info" },
          { id: "summary", label: "场次摘要", value: 1510000, share: 18, tone: "warn" },
          { id: "retry", label: "失败重试", value: 1598700, share: 19, tone: "error" },
        ],
        bySubsystem: [
          { id: "provider", label: "Provider 请求", value: 37, share: 37, tone: "ok", helperText: "成本主体仍在生成层" },
          { id: "planner", label: "观众编排", value: 25, share: 25, tone: "info", helperText: "编排评估次数持续上升" },
          { id: "memory", label: "记忆层", value: 21, share: 21, tone: "warn", helperText: "长期记忆读多写少" },
          { id: "emitter", label: "投递层", value: 17, share: 17, tone: "error", helperText: "高峰时段存在挤压" },
        ],
      },
    },
  },
  audience: {
    defaultAudienceId: "a-li",
    audiences: [
      {
        id: "a-li",
        name: "阿黎",
        tagLine: "高活跃 / 熟客 / 轻度付费",
        summary: "偏吐槽型熟客，喜欢接主播口癖和场面梗，常承担冷场启动。",
        roleTags: ["接梗快", "高活跃", "轻吐槽"],
        activityLevel: "high",
        activityLabel: "高活跃",
        spendingTier: "medium",
        spendingLabel: "中消费",
        relationship: "core",
        relationshipLabel: "核心熟客",
        appearanceFrequency: "几乎每场都在",
        languageStyle: "短句吐槽 + 轻微阴阳，但不会越界。",
        preferences: [
          { label: "互动偏好", detail: "喜欢主播自嘲、翻车补救和节奏拉扯。", strength: "强" },
          { label: "礼物倾向", detail: "更偏好低额礼物和集中刷屏配合。", strength: "中" },
          { label: "回避项", detail: "不喜欢长时间技术调试和空镜头。", strength: "强" },
        ],
        memories: [
          {
            id: "mem-1",
            layer: "长期互动事实",
            summary: "当主播开始念弹幕时，阿黎经常第一时间起头制造连锁互动。",
            confidence: "高置信",
            updatedAt: "昨天 23:14",
          },
          {
            id: "mem-2",
            layer: "观众画像",
            summary: "对主播的自黑式幽默容忍度高，但不喜欢硬切商务口播。",
            confidence: "中置信",
            updatedAt: "3 天前",
          },
        ],
        recentBehaviors: [
          {
            id: "behavior-1",
            happenedAt: "20:41",
            type: "danmaku",
            detail: "在主播改设置时发起“别修了快开播”的吐槽。",
            result: "带动 6 条跟风弹幕",
          },
          {
            id: "behavior-2",
            happenedAt: "20:33",
            type: "gift",
            detail: "配合主播解释 bug 起因送出荧光棒。",
            result: "提升互动密度",
          },
        ],
      },
      {
        id: "bei-jie-zhou",
        name: "北街舟",
        tagLine: "中活跃 / 老观众 / 稳定消费",
        summary: "更像氛围维护者，愿意在合适时机打赏，但讨厌刷屏和过度表演。",
        roleTags: ["氛围维护", "稳定消费", "节奏保守"],
        activityLevel: "medium",
        activityLabel: "中活跃",
        spendingTier: "high",
        spendingLabel: "高消费",
        relationship: "regular",
        relationshipLabel: "稳定观众",
        appearanceFrequency: "每周 3 到 4 场",
        languageStyle: "完整句子、语气平和，偏建议型表达。",
        preferences: [
          { label: "互动偏好", detail: "偏好主播讲解思路、复盘失败原因。", strength: "强" },
          { label: "礼物倾向", detail: "偶尔中额礼物，不喜欢连续高额消费。", strength: "中" },
          { label: "回避项", detail: "排斥太刻意的人设演出。", strength: "中" },
        ],
        memories: [
          {
            id: "mem-3",
            layer: "观众画像",
            summary: "当主播进入复盘模式时，北街舟更可能发送长弹幕或建议型 SC。",
            confidence: "高置信",
            updatedAt: "今天 10:02",
          },
          {
            id: "mem-4",
            layer: "场次摘要",
            summary: "上场直播在高峰段主动提醒主播回收话题，效果良好。",
            confidence: "中置信",
            updatedAt: "昨天 00:12",
          },
        ],
        recentBehaviors: [
          {
            id: "behavior-3",
            happenedAt: "20:36",
            type: "gift",
            detail: "在主播解释系统边界时送出中额礼物。",
            result: "强化正向反馈",
          },
          {
            id: "behavior-4",
            happenedAt: "20:18",
            type: "super_chat",
            detail: "建议下一轮把视觉摘要权重下调。",
            result: "被记为调优建议",
          },
        ],
      },
      {
        id: "tang-shuang",
        name: "糖霜六号",
        tagLine: "低活跃 / 新观众 / 谨慎消费",
        summary: "偶发高价值表达，但稳定性不足，适合作为新观众观察样本。",
        roleTags: ["新观众", "偶发高价值", "不稳定"],
        activityLevel: "low",
        activityLabel: "低活跃",
        spendingTier: "high",
        spendingLabel: "高消费",
        relationship: "new",
        relationshipLabel: "新观众",
        appearanceFrequency: "近两场新出现",
        languageStyle: "比较直接，经常给出目标导向建议。",
        preferences: [
          { label: "互动偏好", detail: "偏好有明确主题和目标的直播段落。", strength: "中" },
          { label: "礼物倾向", detail: "更可能用 SC 提建议，而不是刷普通弹幕。", strength: "强" },
          { label: "回避项", detail: "不喜欢长时间无结果的调试过程。", strength: "强" },
        ],
        memories: [
          {
            id: "mem-5",
            layer: "观众画像",
            summary: "当前画像波动较大，仍需更多场次确认其稳定表达方式。",
            confidence: "低置信",
            updatedAt: "今天 20:05",
          },
        ],
        recentBehaviors: [
          {
            id: "behavior-5",
            happenedAt: "20:40",
            type: "super_chat",
            detail: "建议主播快速切回剧情点评。",
            result: "因 SC 通道关闭被节流",
          },
        ],
      },
      {
        id: "jing-dao",
        name: "镜岛",
        tagLine: "中活跃 / 熟客 / 低消费",
        summary: "偏陪伴型观众，更关注直播氛围完整性和主播个人状态。",
        roleTags: ["陪伴型", "熟客", "低消费"],
        activityLevel: "medium",
        activityLabel: "中活跃",
        spendingTier: "low",
        spendingLabel: "低消费",
        relationship: "regular",
        relationshipLabel: "稳定观众",
        appearanceFrequency: "常出现在收尾时段",
        languageStyle: "更柔和，经常发安抚型短句。",
        preferences: [
          { label: "互动偏好", detail: "偏好主播聊状态、收尾总结和日常碎片。", strength: "中" },
          { label: "礼物倾向", detail: "更可能触发 membership 而不是直接打赏。", strength: "低" },
          { label: "回避项", detail: "不喜欢明显攻击性的观众互喷。", strength: "强" },
        ],
        memories: [
          {
            id: "mem-6",
            layer: "长期互动事实",
            summary: "镜岛常在收尾阶段帮助主播回收节奏，适合做收束型互动。",
            confidence: "高置信",
            updatedAt: "5 天前",
          },
        ],
        recentBehaviors: [
          {
            id: "behavior-6",
            happenedAt: "20:39",
            type: "membership",
            detail: "舰长欢迎语排队中，尚未进入真实平台链路。",
            result: "等待投递队列处理",
          },
        ],
      },
    ],
  },
  review: {
    hostProfile: {
      streamerName: "主播：青栀",
      personaSummary: "反应快、愿意把思路讲给观众听，擅长把调试过程讲成互动内容。",
      languageStyle: "快语速、口头禅稳定，适合高频短弹幕和少量建议型 SC。",
      streamTraits: ["擅长临场接梗", "调试过程可直播化", "高峰时段更适合轻吐槽互动"],
      stableTopics: ["玩法点评", "开发现场", "翻车复盘", "观众接梗"],
      tabooTopics: ["长时间纯静音调试", "连续高额消费暗示", "未经确认的现实人设扩写"],
      updatedAt: "今天 19:58",
    },
    sessionRecaps: [
      {
        id: "session-1",
        dateLabel: "06-17",
        title: "玩法试玩 + 调试并行",
        rhythmLabel: "中段升温明显",
        summary: "主播把一次配置失败转成了临场讲解，互动密度在 15 分钟后明显拉升。",
        peakMoment: "20:46 主播自嘲配置翻车，弹幕接梗形成连续 18 条互动。",
        memoryWrites: 3,
      },
      {
        id: "session-2",
        dateLabel: "06-15",
        title: "剧情点评场",
        rhythmLabel: "稳定平缓",
        summary: "观众更偏向长弹幕和建议型发言，礼物和 SC 占比降低。",
        peakMoment: "21:08 对结局展开争论，适合放大熟客型观众表达。",
        memoryWrites: 2,
      },
      {
        id: "session-3",
        dateLabel: "06-12",
        title: "系统调优预演",
        rhythmLabel: "前冷后热",
        summary: "前半段技术细节过重，后半段通过主播讲述调优目标才恢复互动。",
        peakMoment: "20:32 明确目标后，观众开始集中提建议。",
        memoryWrites: 4,
      },
    ],
    highlights: [
      {
        id: "highlight-1",
        happenedAt: "20:46",
        title: "翻车讲解触发连锁互动",
        detail: "主播主动拆解错误原因后，熟客型观众连续接梗，互动密度迅速抬升。",
        impact: "证明“讲思路”比“闷头修”更能带起实时观众反应。",
      },
      {
        id: "highlight-2",
        happenedAt: "21:08",
        title: "剧情点评吸引建议型观众",
        detail: "当直播进入明确主题讨论时，建议型观众更愿意发长弹幕或 SC。",
        impact: "适合在高峰段安排可讨论议题，提升高质量发言比例。",
      },
      {
        id: "highlight-3",
        happenedAt: "20:32",
        title: "调试目标公开后恢复节奏",
        detail: "明确告诉观众“现在在修什么”后，空场时间明显缩短。",
        impact: "说明需要把上下文窗口中的目标状态更清晰地暴露给前端工作台。",
      },
    ],
    suggestions: [
      {
        id: "suggestion-1",
        category: "直播节奏",
        title: "把调试段落拆成“目标 -> 过程 -> 结论”三段",
        detail: "当前高活跃观众能接受调试，但需要明确每段要解决什么，否则会触发节流和掉线式沉默。",
        priority: "高优先级",
      },
      {
        id: "suggestion-2",
        category: "互动编排",
        title: "在高峰前 5 分钟预热熟客型短弹幕",
        detail: "阿黎、镜岛这类观众更适合做开场与收尾的节奏桥梁，不建议一上来就放高价值互动。",
        priority: "中优先级",
      },
      {
        id: "suggestion-3",
        category: "记忆策略",
        title: "只把稳定偏好写入长期层，新观众先停留在场次摘要",
        detail: "糖霜六号这类画像仍不稳定，先保留为场次观察记录，避免过早固化。",
        priority: "高优先级",
      },
    ],
  },
};
