import type { BigVWorkbenchSnapshot } from "./types";

export const BIGV_WORKBENCH_SNAPSHOT: BigVWorkbenchSnapshot = {
  nav: [
    {
      key: "danmaku",
      label: "弹幕姬",
      to: "/danmaku",
      description: "实时互动流、投递状态与启停控制",
    },
    {
      key: "quota",
      label: "额度检查",
      to: "/quota",
      description: "查看请求消耗、token 走势与子系统拆分",
    },
    {
      key: "audience",
      label: "观众信息",
      to: "/audience",
      description: "观众人设、长期记忆和互动偏好",
    },
    {
      key: "review",
      label: "直播回顾",
      to: "/review",
      description: "主播画像、场次摘要、高光行为与建议",
    },
  ],
  danmaku: {
    liveStatus: {
      roomLabel: "本地单直播间 / 房间 1001",
      streamTitle: "晚间试玩 + 主播语音主链路验证",
      statusLabel: "模拟直播中",
      tone: "warn",
      viewerEstimate: 186,
      rhythmLabel: "平稳升温",
      nextActionHint: "当前允许轻量礼物和高频弹幕，暂不建议连续 SC。",
      updatedAt: "2 分钟前",
    },
    inputSources: [
      {
        key: "voice",
        label: "主播语音",
        statusLabel: "待输入",
        tone: "info",
        summary: "等待本地 ASR 或手动面板提交主播语音文本。",
      },
      {
        key: "echo-live",
        label: "Echo-Live",
        statusLabel: "未连接",
        tone: "info",
        summary: "等待 Echo-Live WebSocket 文本输入。",
      },
      {
        key: "vision",
        label: "视觉上下文",
        statusLabel: "预留接口",
        tone: "info",
        summary: "视觉摘要输入接口已预留，阶段 3 不处理原始视频流。",
      },
    ],
    contextEvents: [],
    contextWindowSeconds: 300,
    toggles: [
      {
        key: "dispatch",
        label: "自动投递",
        description: "控制本地模拟事件是否进入互动渲染队列。",
        enabled: true,
      },
      {
        key: "gifts",
        label: "礼物通道",
        description: "允许生成 gift 与 membership 相关互动。",
        enabled: true,
      },
      {
        key: "super-chat",
        label: "SC 通道",
        description: "高价值互动默认谨慎开启，用于节奏验证。",
        enabled: false,
      },
      {
        key: "memory-write",
        label: "记忆写回预演",
        description: "仅展示前端状态，不会写入真实记忆库。",
        enabled: true,
      },
    ],
    queueStats: [
      { type: "danmaku", label: "弹幕", queued: 12, delivered: 148, throttled: 6 },
      { type: "gift", label: "礼物", queued: 2, delivered: 16, throttled: 1 },
      { type: "super_chat", label: "SC", queued: 0, delivered: 3, throttled: 2 },
      { type: "membership", label: "舰长", queued: 1, delivered: 4, throttled: 0 },
    ],
    recentEvents: [
      {
        id: "evt-1",
        type: "danmaku",
        audienceName: "阿黎",
        content: "这一段反应好快，像是真的在跟弹幕对线。",
        statusLabel: "已投递",
        tone: "ok",
        happenedAt: "20:41:13",
      },
      {
        id: "evt-2",
        type: "gift",
        audienceName: "北街舟",
        content: "送出荧光棒 x2，配合主播刚提到的新梗。",
        amountLabel: "¥20",
        statusLabel: "已投递",
        tone: "ok",
        happenedAt: "20:40:57",
      },
      {
        id: "evt-3",
        type: "super_chat",
        audienceName: "糖霜六号",
        content: "建议下一段切回剧情点评，不要一直卡在设置界面。",
        amountLabel: "¥30",
        statusLabel: "被节流",
        tone: "warn",
        happenedAt: "20:40:28",
      },
      {
        id: "evt-4",
        type: "membership",
        audienceName: "镜岛",
        content: "触发舰长入场欢迎，但尚未进入真实平台链路。",
        statusLabel: "排队中",
        tone: "info",
        happenedAt: "20:39:49",
      },
    ],
    blivechatChannels: [],
    mockSource: {
      state: "idle",
      scenarioLabel: "本地直播循环",
      tickCount: 0,
      intervalMs: 2500,
    },
    mockSourceRecords: [],
    simulationStatus: {
      rhythmState: "cold",
      rhythmLabel: "冷场观察",
      activeAudienceCount: 0,
      plannedIntentCount: 0,
      llmBatchCallCount: 0,
      localGeneratedCount: 0,
      cooldownRejectCount: 0,
      throttleRejectCount: 0,
      budgetRejectCount: 0,
      memoryAudienceCount: 0,
      shadowAudienceCount: 240,
    },
    notices: [
      {
        id: "notice-2",
        title: "SC 通道关闭",
        detail: "当前仅做前端模拟，不建议持续放开高价值互动。",
        tone: "info",
      },
      {
        id: "notice-3",
        title: "记忆写回未接通",
        detail: "页面仅演示写回条件与提示，不会污染真实长期记忆。",
        tone: "warn",
      },
    ],
  },
  quota: {
    defaultWindow: "24h",
    windows: [
      { key: "24h", label: "24 小时" },
      { key: "7d", label: "7 天" },
      { key: "30d", label: "30 天" },
    ],
    windowData: {
      "24h": {
        summary: {
          requestCount: 246,
          inputTokens: 318400,
          outputTokens: 92600,
          estimatedCost: 38.72,
          retryWasteTokens: 18240,
        },
        trend: [
          { label: "00", inputTokens: 22400, outputTokens: 6400, retryWasteTokens: 1200, estimatedCost: 2.64 },
          { label: "04", inputTokens: 18800, outputTokens: 5400, retryWasteTokens: 900, estimatedCost: 2.18 },
          { label: "08", inputTokens: 49200, outputTokens: 12600, retryWasteTokens: 2400, estimatedCost: 5.78 },
          { label: "12", inputTokens: 64200, outputTokens: 16300, retryWasteTokens: 3500, estimatedCost: 7.42 },
          { label: "16", inputTokens: 74500, outputTokens: 21600, retryWasteTokens: 4400, estimatedCost: 9.24 },
          { label: "20", inputTokens: 89300, outputTokens: 30300, retryWasteTokens: 5840, estimatedCost: 11.46 },
        ],
        byModel: [
          { id: "gpt-4.1-mini", label: "gpt-4.1-mini", value: 214000, share: 52, tone: "ok" },
          { id: "gpt-4.1", label: "gpt-4.1", value: 121000, share: 29, tone: "warn" },
          { id: "embedding", label: "text-embedding-3-small", value: 76000, share: 19, tone: "info" },
        ],
        byCapability: [
          { id: "gen", label: "互动生成", value: 196000, share: 48, tone: "ok" },
          { id: "memory", label: "记忆检索", value: 94000, share: 23, tone: "info" },
          { id: "summary", label: "场次摘要", value: 62000, share: 15, tone: "warn" },
          { id: "retry", label: "失败重试", value: 58240, share: 14, tone: "error" },
        ],
        bySubsystem: [
          { id: "provider", label: "Provider 请求", value: 41, share: 41, tone: "ok", helperText: "峰值每小时 18 次" },
          { id: "planner", label: "观众编排", value: 24, share: 24, tone: "info", helperText: "含频率控制预演" },
          { id: "memory", label: "记忆层", value: 21, share: 21, tone: "warn", helperText: "写回仍为模拟" },
          { id: "emitter", label: "投递层", value: 14, share: 14, tone: "error", helperText: "节流主要发生在 SC 通道" },
        ],
      },
      "7d": {
        summary: {
          requestCount: 1286,
          inputTokens: 1723400,
          outputTokens: 498600,
          estimatedCost: 216.84,
          retryWasteTokens: 94520,
        },
        trend: [
          { label: "周一", inputTokens: 186000, outputTokens: 53600, retryWasteTokens: 10400, estimatedCost: 23.82 },
          { label: "周二", inputTokens: 204800, outputTokens: 59200, retryWasteTokens: 11200, estimatedCost: 26.14 },
          { label: "周三", inputTokens: 232600, outputTokens: 67400, retryWasteTokens: 12920, estimatedCost: 29.36 },
          { label: "周四", inputTokens: 218400, outputTokens: 62300, retryWasteTokens: 12000, estimatedCost: 27.48 },
          { label: "周五", inputTokens: 262700, outputTokens: 76800, retryWasteTokens: 14800, estimatedCost: 33.62 },
          { label: "周六", inputTokens: 318900, outputTokens: 93000, retryWasteTokens: 18000, estimatedCost: 40.08 },
          { label: "周日", inputTokens: 300000, outputTokens: 86300, retryWasteTokens: 15200, estimatedCost: 36.34 },
        ],
        byModel: [
          { id: "gpt-4.1-mini", label: "gpt-4.1-mini", value: 1128000, share: 51, tone: "ok" },
          { id: "gpt-4.1", label: "gpt-4.1", value: 656000, share: 30, tone: "warn" },
          { id: "embedding", label: "text-embedding-3-small", value: 437000, share: 19, tone: "info" },
        ],
        byCapability: [
          { id: "gen", label: "互动生成", value: 936000, share: 42, tone: "ok" },
          { id: "memory", label: "记忆检索", value: 514000, share: 23, tone: "info" },
          { id: "summary", label: "场次摘要", value: 398000, share: 18, tone: "warn" },
          { id: "retry", label: "失败重试", value: 373000, share: 17, tone: "error" },
        ],
        bySubsystem: [
          { id: "provider", label: "Provider 请求", value: 39, share: 39, tone: "ok", helperText: "平均成功率 93%" },
          { id: "planner", label: "观众编排", value: 23, share: 23, tone: "info", helperText: "高峰时段策略更活跃" },
          { id: "memory", label: "记忆层", value: 22, share: 22, tone: "warn", helperText: "摘要轮次明显增加" },
          { id: "emitter", label: "投递层", value: 16, share: 16, tone: "error", helperText: "重试主要来自事件拥塞" },
        ],
      },
      "30d": {
        summary: {
          requestCount: 4820,
          inputTokens: 6482300,
          outputTokens: 1921400,
          estimatedCost: 804.16,
          retryWasteTokens: 322600,
        },
        trend: [
          { label: "第 1 周", inputTokens: 1408200, outputTokens: 416000, retryWasteTokens: 70200, estimatedCost: 174.28 },
          { label: "第 2 周", inputTokens: 1563600, outputTokens: 462400, retryWasteTokens: 78100, estimatedCost: 193.54 },
          { label: "第 3 周", inputTokens: 1679500, outputTokens: 498600, retryWasteTokens: 84600, estimatedCost: 208.76 },
          { label: "第 4 周", inputTokens: 1831000, outputTokens: 544400, retryWasteTokens: 89700, estimatedCost: 227.58 },
        ],
        byModel: [
          { id: "gpt-4.1-mini", label: "gpt-4.1-mini", value: 4140000, share: 49, tone: "ok" },
          { id: "gpt-4.1", label: "gpt-4.1", value: 2570000, share: 31, tone: "warn" },
          { id: "embedding", label: "text-embedding-3-small", value: 1691700, share: 20, tone: "info" },
        ],
        byCapability: [
          { id: "gen", label: "互动生成", value: 3460000, share: 41, tone: "ok" },
          { id: "memory", label: "记忆检索", value: 1890000, share: 22, tone: "info" },
          { id: "summary", label: "场次摘要", value: 1510000, share: 18, tone: "warn" },
          { id: "retry", label: "失败重试", value: 1598700, share: 19, tone: "error" },
        ],
        bySubsystem: [
          { id: "provider", label: "Provider 请求", value: 37, share: 37, tone: "ok", helperText: "成本主体仍在生成层" },
          { id: "planner", label: "观众编排", value: 25, share: 25, tone: "info", helperText: "编排评估次数持续上升" },
          { id: "memory", label: "记忆层", value: 21, share: 21, tone: "warn", helperText: "长期记忆读多写少" },
          { id: "emitter", label: "投递层", value: 17, share: 17, tone: "error", helperText: "高峰时段存在挤压" },
        ],
      },
    },
  },
  audience: {
    defaultAudienceId: "",
    audiences: [],
  },
  review: {
    hostProfile: {
      streamerName: "",
      personaSummary: "",
      languageStyle: "",
      streamTraits: [],
      stableTopics: [],
      tabooTopics: [],
      updatedAt: "",
    },
    sessionRecaps: [],
    highlights: [],
    suggestions: [],
  },
};
